version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - camonprefect-app:latest
    user: vscode
    volumes:
      - ..:/workspaces/CamOnPrefect  # Maps entire project directory
    environment:
      - DLT_TELEMETRY=off
      - DBT_PROFILES_DIR=/workspaces/CamOnPrefect/dbt
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql://prefect:prefect@postgres:5432/prefect
    working_dir: /workspaces/CamOnPrefect  # Matches volume mount
    depends_on:  # Add this section
      postgres:
        condition: service_healthy
    networks:
      - prefect-net

  # Add this new service for PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U '${POSTGRES_USER}' -d '${POSTGRES_DB}'"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prefect-net

volumes:
  postgres_data:  # Persists database data

networks:
  prefect-net:
    driver: bridge