name: Check Python Dependencies

on:
  schedule:
    - cron: '10 12 * * 4' # Runs at 10:10pm Thursday Melbourne time (AEST, UTC+10)
  workflow_dispatch:

jobs:
  pip-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip list --outdated --format=columns | grep -F -f <(grep -vE '^\s*#|^\s*$' requirements.txt | cut -d= -f1)