name: Scheduled UV Pipeline

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 09:00 UTC (8pm Melbourne during daylight saving)
  workflow_dispatch:

jobs:
  run-uv-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: Run UV Prefect Pipeline
        env:
          UV_API_KEY: ${{ secrets.UV_API_KEY }}
          DLT_DESTINATION: ${{ secrets.DLT_DESTINATION }}
          DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD: ${{ secrets.DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD }}
          DESTINATION__MOTHERDUCK__CREDENTIALS__DATABASE: ${{ secrets.DESTINATION__MOTHERDUCK__CREDENTIALS__DATABASE }}
          MOTHERDUCK_CREDENTIALS: ${{ secrets.MOTHERDUCK_CREDENTIALS }}
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
          PYTHONPATH: ${{ github.workspace }}
          PYTHONWARNINGS: ignore::UserWarning
        run: python pipelines/uv_prefect.py